"""fix

Revision ID: 1799c4c6c4e0
Revises: 68c9a89bfe60
Create Date: 2025-03-18 04:07:21.690916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1799c4c6c4e0'
down_revision: Union[str, None] = '68c9a89bfe60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'currency_name_for_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('currency_name_for_bot', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
