"""fix

Revision ID: 68c9a89bfe60
Revises: d1d8cd4dd025
Create Date: 2025-03-18 04:02:59.561362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c9a89bfe60'
down_revision: Union[str, None] = 'd1d8cd4dd025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('buy_value', sa.String(), nullable=True))
    op.add_column('currencies', sa.Column('sell_value', sa.String(), nullable=True))
    op.drop_column('currencies', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('currencies', 'sell_value')
    op.drop_column('currencies', 'buy_value')
    # ### end Alembic commands ###
